# API

## Login
POST http://localhost:9091/admin/login
Content-Type: application/json

{
    "email": "wuttgipong-k@rmutp.ac.th", 
    "password": "0925480818Za", 
    "rememberMe": false
}

## Forgot
## Profile
## Register / Signup