services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      
54327:5432
  environment:
POSTGRES_PASSWORD=0925480818Za
POSTGRES_USER=wutthipong
POSTGRES_DB=wutthipong
volumes:
./data:/var/lib/postgresql/data
